countrycollector/countrycollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

countrycollector/main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name ='home'),
    path('about/', views.about, name ='about'),
    path('countries/', views.countries_index, name='index'),
    path('countries/new/', views.new_country, name='new_country'),
    path('countries/<int:country_id>/', views.countries_detail, name='detail'),
    path('countries/<int:countries_id>/edit', views.countries_update, name='countries_update'),
    path('countries/<int:countries_id>/delete', views.countries_delete, name='countries_delete'),
    path('countries/<int:country_id>/add_city', views.add_city, name='add_city'),
    path('countries/<int:country_id>/assoc_cruise/<int:cruise_id>/', views.assoc_cruise, name='assoc_cruise'),
    path('cruises/', views.CruiseList.as_view(), name='cruises_index'),
    path('cruises/<int:pk>/', views.CruiseDetail.as_view(), name='cruises_detail'),
    path('cruises/create/', views.CruiseCreate.as_view(), name='cruises_create'),
    path('cruises/<int:pk>/update/', views.CruiseUpdate.as_view(), name='cruises_update'),
    path('cruises/<int:pk>/delete/', views.CruiseDelete.as_view(), name='cruises_delete')
]

countrycollector/main_app/models.py
from django.db import models
from django.urls import reverse

RIVERS = (
    ('D', 'Danube'), 
    ('E', 'Elbe'),  
    ('R', 'Rhone')
    )

# Create your models here.
class RiverCruise(models.Model):
    name = models.CharField(max_length=100)
    river = models.CharField(
        max_length=1,
        choices=RIVERS,
        default=RIVERS[0][0]
    )

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('cruises_detail', kwargs={'pk': self.id})

class Country(models.Model):
    name = models.CharField(max_length=100)
    continent = models.CharField(max_length=100)
    language = models.CharField(max_length=100)
    visited = models.BooleanField()
    cruises = models.ManyToManyField(RiverCruise)

    def __str__(self):
        return self.name

class City(models.Model):
    name = models.CharField(max_length=100)
    visited = models.BooleanField()
    what_to_eat = models.TextField(max_length=250)

    country = models.ForeignKey(Country, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['name']

countrycollector/main_app/forms.py
from django import forms
from .models import Country, City

class CountryForm(forms.ModelForm):
    class Meta:
        model = Country
        fields = ['name', 'visited', 'language', 'continent']

class CityForm(forms.ModelForm):

    class Meta:
        model = City
        fields = ['name', 'visited', 'what_to_eat']

countrycollector/main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Country, City, RiverCruise
from .forms import CountryForm, CityForm
# Create your views here.
def home(request):
  return render (request, 'home.html')

def about(request):
    return render(request, 'about.html')

def countries_index(request):
    countries = Country.objects.all()
    return render(request, 'countries/index.html', { 'countries': countries })

def countries_detail(request, country_id):
    country = Country.objects.get(id = country_id)
    cruises_country_doesnt_have = RiverCruise.objects.exclude(id__in = country.cruises.all().values_list('id'))
    city_form = CityForm()
    return render(request, 'countries/detail.html', { 
        'country': country,
        'city_form': city_form,
        'cruises': cruises_country_doesnt_have
        })

def add_city(request, country_id):
    form = CityForm(request.POST)
    if form.is_valid():
        new_city = form.save(commit=False)
        new_city.country_id = country_id
        new_city.save()
    return redirect('detail', country_id=country_id)

def assoc_cruise(request, country_id, cruise_id):
    Country.objects.get(id=country_id).cruises.add(cruise_id)
    return redirect('detail', country_id=country_id)

def new_country(request):
  if request.method == 'POST':
    form = CountryForm(request.POST)
    if form.is_valid():
      country = form.save()
      return redirect('detail', country.id)
  else:
    form = CountryForm()
    context = { 'form': form }
  return render(request, 'countries/country_form.html', context)

def countries_update(request, country_id):
  # Select the cat that we're updating from the DB
  country = Country.objects.get(id=country_id)

  # If the request is a POST
  if request.method == "POST":
    form = CountryForm(request.POST, instance=country)
    if form.is_valid():
      country = form.save()
      return redirect('detail', country.id)
  # If not a POST, create the form
  else: 
    form = CountryForm(instance=country)
  # Render the form by sending the context to our existing template
  return render(request, 'countries/country_form.html', { 'form': form })

def countries_delete(request, country_id):
  Country.objects.get(id=country_id).delete()
  return redirect('index')



class CruiseList(ListView):
    model = RiverCruise

class CruiseDetail(DetailView):
    model = RiverCruise

class CruiseCreate(CreateView):
    model = RiverCruise
    fields = '__all__'

class CruiseUpdate(UpdateView):
    model = RiverCruise
    fields = ['name', 'type']

class CruiseDelete(DeleteView):
    model = RiverCruise
    success_url = '/cruises/'

countrycollector/main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

  <h1>About the Country Collector</h1>
<hr />
<p>Hire the Country Collector!</p>

{% endblock %}

countrycollector/main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Country Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;CountryCollector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'cruises_create' %}">Add a River Cruise</a></li>
          <li><a href="{% url 'cruises_index' %}">View All River Cruises</a></li>
          <li><a href="{% url 'new_country' %}">Add a Country</a></li>
          <li><a href="{% url 'index' %}">View All Countries</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2020 Country Collector &nbsp;</div>
  </footer>
</body>
</html>

countrycollector/main_app/templates/countries/country_form.html
{% extends 'base.html' %}

{% block content %}
    <section class="form-section">
        <h1>Add a Country</h1>
        <form  method="POST" class="artist-form">
            {% csrf_token %}
            {{form.as_p}}
            <button class="btn" type="submit">Save</button>
        </form>
    </section>

<script>
    let visitedEl = document.getElementById('id_visited')
    let labelEl = document.querySelector('label[for = id_visited]')
    labelEl.innerHTML += '<span></span>'
    labelEl.prepend(visitedEl)
</script>
{% endblock %}

countrycollector/main_app/templates/countries/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Country Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ country.name }}</span>
        <p>Continent: {{ country.continent }}</p>
        <p>Language: {{ country.language }}</p>
        {% if country.visited == True %}
          <p>Visited: Yes!</p>
        {% else %}
          <p>Visited: Not yet!</p>
        {% endif %}
      </div>

      <div class="card-action">
        <a href="{% url 'countries_update' country.id %}">EDIT</a>
        <a href="{% url 'countries_delete' country.id %}">DELETE</a>
    </div>
  </div>
  <div class="col s6">
    <form action="{% url 'add_city' country.id %}" method="post">
     {% csrf_token %}
     {{ city_form.as_p }}
     <input type="submit" class="btn" value="Add City">
     </form>
    <table class="striped">
      <thead>
        <tr><th>City</th><th>Eats</th><th>Visited?</th>
      </thead>
      <tbody>
        {% for city in country.city_set.all %}
          <tr>
            <td>{{city.name}}</td>
            <td>{{city.what_to_eat}}</td>
            {% if city.visited == True %}
                <td>Yes!</td>
            {% else %}
                <td>Not yet!</td>
            {% endif %}
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
  <hr>
<div class="row">
  <div class="col s6">
    <h3>{{ country.name }}'s Cruises</h3>
    {% if country.cruises.count %}
      {% for cruise in country.cruises.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              <span>{{ cruise.name }}</span><br>River: {{ cruise.get_river_display }}
            </span>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Cruises :(</h5>
    {% endif %}
  </div>
  <div class="col s6">
    <h3>Available Cruises</h3>
    {% if cruises.count %}
      {% for cruise in cruises.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              <span>{{ cruise.name }}</span><br>River: {{ cruise.get_river_display }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_cruise' country.id cruise.id %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{country.name}} Already Has All Cruises Available</h5>
    {% endif %}
  </div>
</div>
<script>
    let visitedEl = document.getElementById('id_visited')
    let labelEl = document.querySelector('label[for = id_visited]')
    labelEl.innerHTML += '<span></span>'
    labelEl.prepend(visitedEl)
</script>

{% endblock %}

countrycollector/main_app/templates/countries/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Country List</h1>

{% for country in countries %}
  <div class="card">
    <div class="card-content">
      <span class="card-title">{{ country.name }}</span>
      <p>Continent: {{ country.continent }}</p>
      <p>Language: {{ country.language }}</p>
      {% if country.visited == True %}
        <p>Visited: Yes!</p>
      {% else %}
        <p>Visited: Not Yet!</p>
      {% endif %}
    </div>
  </div>
{% endfor %}

{% endblock %}

countrycollector/main_app/templates/home.html
{% extends 'base.html' %}

{% block content %}
    <h1>Welcome to CountryCollector</h1>
{% endblock content %}

countrycollector/main_app/templates/main_app/rivercruise_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete River Cruise</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'cruises_detail' object.id %}">Cancel</a>
  </form>
{% endblock %} 

countrycollector/main_app/templates/main_app/rivercruise_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>River Cruise Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ rivercruise.name }}</span>
        <p>River: {{ rivercruise.river }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'cruises_update' rivercruise.id %}">Edit</a>
        <a href="{% url 'cruises_delete' rivercruise.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

countrycollector/main_app/templates/main_app/rivercruise_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add River Cruise</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>

<script>
  let selectEl = document.getElementById('id_river');
  M.FormSelect.init(selectEl);
</script>
{% endblock %}

countrycollector/main_app/templates/main_app/rivercruise_list.html
{% extends 'base.html' %}
{% block content %}

<h1>River Cruise List</h1>

{% for rivercruise in rivercruise_list %}
  <a href="{% url 'cruises_detail' rivercruise.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ rivercruise.name }}</span>
            <p>River: {{ rivercruise.river }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %} 